name: JavaCI

env:
  MAVEN_OPT: -q

on:
  # Acione o fluxo de trabalho na solicitação push ou pull,
  # mas apenas para a ramificação principal.
  push:
    branches:
    - master
    - develop
    - 'release/**'
    tags:        
    - v*
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '**.json'
    - '**.yml'
  pull_request:
    branches:
    - master
    - develop
    - 'release/**'
    tags:        
    - v*

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup java
      uses: joschi/setup-jdk@v1
      env:
        CODECOVTOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        java-version: 'openjdk11'
        architecture: 'x64'
    - name: Test with Maven
      run: |
        mvn ${MAVEN_OPT} -am clean test jacoco:report
        bash <(curl -s https://codecov.io/bash) -t $CODECOVTOKEN
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup java
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk11'
        architecture: 'x64'
    - name: Build with Maven
      run: |
        mvn ${MAVEN_OPT} -am clean package install